# Generated by Django 5.1.5 on 2025-02-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0002_remove_watchlist_review_text_movie_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
