# Generated by Django 5.1.5 on 2025-02-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0007_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
