# Generated by Django 5.1.5 on 2025-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0009_alter_movie_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_path', models.CharField(max_length=255)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('poster_url', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
