# Generated by Django 5.1.5 on 2025-02-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0010_tvshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='first_air_date',
            new_name='release_date',
        ),
    ]
