# Generated by Django 5.1.5 on 2025-02-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0011_rename_first_air_date_tvshow_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tv_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_reviews.tvshow'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_reviews.movie'),
        ),
    ]
