# Generated by Django 5.1.5 on 2025-02-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0012_review_tv_show_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(default='https://dummyimage.com/500x750/000000/ffffff.jpg&text=No+Image+Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='poster_url',
            field=models.CharField(default='https://dummyimage.com/500x750/000000/ffffff.jpg&text=No+Image+Available', max_length=250),
        ),
    ]
