# Generated by Django 5.1.5 on 2025-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0013_alter_movie_poster_url_alter_tvshow_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='poster_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
