# Generated by Django 5.1.5 on 2025-02-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0014_alter_movie_poster_url_alter_tvshow_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='poster_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
